export const API_DATA_FETCHED = 'API_DATA_FETCHED';
export const API_DATA_FETCH_FAILED = 'API_DATA_FETCH_FAILED';
export const ITEM_ADDED_TO_API = 'ITEM_ADDED_TO_API';
export const ITEM_ADDED_TO_API_FAILED = 'ITEM_ADDED_TO_API_FAILED';
