FROM node:10-alpine

WORKDIR /usr/src/app

ENV NODE_ENV=production

RUN yarn global add lerna

COPY ./package.json .
RUN yarn install --no-lockfile

COPY ./packages/emitter /usr/src/app/packages/emitter
EXPOSE 5000

COPY lerna.json .
RUN lerna bootstrap

CMD ["yarn", "dev:emitter"]