export const FETCH_API_DATA_REQUEST = 'FETCH_API_DATA_REQUEST';
export const FETCH_API_DATA_SUCCESS = 'FETCH_API_DATA_SUCCESS';
export const FETCH_API_DATA_FAILED = 'FETCH_API_DATA_FAILED';
export const ADD_ITEM_TO_API_REQUEST = 'ADD_ITEM_TO_API_REQUEST';
export const ADD_ITEM_TO_API_SUCCESS = 'ADD_ITEM_TO_API_SUCCESS';
export const ADD_ITEM_TO_API_FAILED = 'ADD_ITEM_TO_API_FAILED';
export const DELETE_API_ITEM_REQUEST = 'DELETE_API_ITEM_REQUEST';
